package com.be.registry;

import javax.annotation.Nonnull;

import org.bukkit.Color;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;
import org.jetbrains.annotations.Nullable;

import io.github.thebusybiscuit.exoticgarden.CustomPotion;
import io.github.thebusybiscuit.exoticgarden.ExoticGarden;
import io.github.thebusybiscuit.exoticgarden.items.CustomFood;
import io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem;
import io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack;
import io.github.thebusybiscuit.slimefun4.api.recipes.RecipeType;
import io.github.thebusybiscuit.slimefun4.implementation.SlimefunItems;
import io.github.thebusybiscuit.slimefun4.implementation.items.food.Juice;

public class BEFoodRegistry {

    public static void register(@Nonnull ExoticGarden plugin) {
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("BREADFRUIT_JUICE", new CustomPotion("&2异域面包果酱", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("BREADFRUIT"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("BREADFRUIT_ICED_JUICE", new CustomPotion("&d冰镇异域面包果汁", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("BREADFRUIT"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("BIG_CARROT_JUICE", new CustomPotion("&4萝卜酱", Color.RED, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("BIG_CARROT"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("BIG_CARROT_ICED_JUICE", new CustomPotion("&4冰镇萝卜果汁", Color.RED, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("BIG_CARROT"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new CustomFood(ExoticGarden.instance.foodItemGroup, new SlimefunItemStack("BE_HAMBUGER", "a411cb54aaa1e3db555c785f6b75be1bf8e68b28e5cfc59c9a876894f61cdc17", "&r汉堡包", "", "&7&o恢复 &b&o5 &7&o点饥饿值"), new ItemStack[]{new ItemStack(Material.BREAD), new ItemStack(Material.MILK_BUCKET), new ItemStack(Material.BEETROOT), null, null, null, null, null, null}, 10)).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("ALIEN_FRUIT_JUICE", new CustomPotion("&2外星果酱", Color.PURPLE, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("ALIEN_FRUIT"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("ALIEN_FRUIT_ICED_JUICE", new CustomPotion("&d冰镇外星果汁", Color.PURPLE, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("ALIEN_FRUIT"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("PUNCH_FRUIT_JUICE", new CustomPotion("&2潘趣果酱", Color.BLUE, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("PUNCH_FRUIT"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("PUNCH_FRUIT_ICED_JUICE", new CustomPotion("&d冰镇潘趣果汁", Color.BLUE, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("PUNCH_FRUIT"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("BIG_WHEAT_JUICE", new CustomPotion("&2异域大麦酱", Color.YELLOW, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("BIG_WHEAT"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("BIG_WHEAT_ICED_JUICE", new CustomPotion("&d冰镇异域大麦汁", Color.YELLOW, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("BIG_WHEAT"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("AMARANTH_JUICE", new CustomPotion("&2异域苋菜酱", Color.RED, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("AMARANTH"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("AMARANTH_ICED_JUICE", new CustomPotion("&d冰镇异域苋菜汁", Color.RED, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("AMARANTH"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        //(new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("PISTACHIO_JUICE", new CustomPotion("&2开心果酱", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("PISTACHIO"), null, null, null, null, null, null, null, null})).register(plugin);
        //(new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("PISTACHIO_ICED_JUICE", new CustomPotion("&d冰镇开心果汁", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("PISTACHIO"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("OTHER_PEANUT_JUICE", new CustomPotion("&2异域花生泥", Color.PURPLE, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("PEANUT"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("PEANUT_ICED_JUICE", new CustomPotion("&d冰镇异域花生汁", Color.PURPLE, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("PEANUT"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("MEXICO_CHILI_JUICE", new CustomPotion("&2异域墨西哥辣椒酱", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("MEXICO_CHILI"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("MEXICO_CHILI_ICED_JUICE", new CustomPotion("&d冰镇异域墨西哥辣椒汁", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("MEXICO_CHILI"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("INFERNOFRUIT_JUICE", new CustomPotion("&2地狱果酱", Color.RED, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("INFERNOFRUIT"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("INFERNOFRUIT_ICED_JUICE", new CustomPotion("&d冰镇地狱果汁", Color.RED, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("INFERNOFRUIT"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("ACORN_SQUASH_JUICE", new CustomPotion("&2异域橡子南瓜酱", Color.GRAY, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("ACORN_SQUASH"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("ACORN_SQUASH_ICED_JUICE", new CustomPotion("&d冰镇异域橡子南瓜汁", Color.GRAY, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("ACORN_SQUASH"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("ROSE_JUICE", new CustomPotion("&2异域玫瑰酱", Color.RED, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("ROSE"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("ROSE_ICED_JUICE", new CustomPotion("&d冰镇异域玫瑰汁", Color.RED, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("ROSE"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("SAKURA_JUICE", new CustomPotion("&2异域樱花酱", Color.PURPLE, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("SAKURA"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("SAKURA_ICED_JUICE", new CustomPotion("&d冰镇异域樱花汁", Color.PURPLE, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("SAKURA"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("REED_JUICE", new CustomPotion("&2异域甘蔗酱", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("REED"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("REED_ICED_JUICE", new CustomPotion("&d冰镇异域甘蔗汁", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("REED"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("ALOE_JUICE", new CustomPotion("&2异域芦荟酱", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("ALOE"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("ALOE_ICED_JUICE", new CustomPotion("&d冰镇异域芦荟汁", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("ALOE"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("PURPLE_FLOWER_JUICE", new CustomPotion("&2紫花酱", Color.PURPLE, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("PURPLE_FLOWER"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("PURPLE_FLOWER_ICED_JUICE", new CustomPotion("&d冰镇紫花汁", Color.PURPLE, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("PURPLE_FLOWER"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("PURPLE_ROSE_JUICE", new CustomPotion("&2紫色玫瑰酱", Color.PURPLE, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("PURPLE_ROSE"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("PURPLE_ROSE_ICED_JUICE", new CustomPotion("&d冰镇紫色玫瑰汁", Color.PURPLE, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("PURPLE_ROSE"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("MANDRAKE_ROOT_JUICE", new CustomPotion("&2异域曼德拉根酱", Color.ORANGE, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("MANDRAKE_ROOT"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("MANDRAKE_ROOT_ICED_JUICE", new CustomPotion("&d冰镇异域曼德拉根汁", Color.ORANGE, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("MANDRAKE_ROOT"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("JACKFRUIT_JUICE", new CustomPotion("&2异域菠萝蜜酱", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("JACKFRUIT"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("JACKFRUIT_ICED_JUICE", new CustomPotion("&d冰镇异域菠萝蜜汁", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("JACKFRUIT"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("DEVIL_MELON_JUICE", new CustomPotion("&2异域恶魔瓜酱", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 6, 0), "", "&7&o恢复 &b&o3.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("DEVIL_MELON"), null, null, null, null, null, null, null, null})).register(plugin);
        (new Juice(ExoticGarden.instance.drinksItemGroup, new SlimefunItemStack("DEVIL_MELON_ICED_JUICE", new CustomPotion("&d冰镇异域恶魔瓜汁", Color.GREEN, new PotionEffect(PotionEffectType.SATURATION, 10, 0), "", "&7&o恢复 &b&o5.0 &7&o点饥饿值")), RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[]{getItem("DEVIL_MELON"), getItem("ICE_CUBE"), null, null, null, null, null, null, null})).register(plugin);
        (new CustomFood(ExoticGarden.instance.foodItemGroup, new SlimefunItemStack("BE_FRIED_POTETO", "6a82e11d5a64c6d653f3a1c53c9420a153818e67dbd8e93442c35c627e0c631", "&r薯条", "", "&7&o恢复 &b&o4.0 &7&o点饥饿值"), new ItemStack[]{new ItemStack(SlimefunItems.WHEAT_FLOUR.item()), new ItemStack(Material.POTATO), new ItemStack(Material.POTATO), null, null, null, null, null, null}, 8)).register(plugin);
    }

    @Nullable
    private static ItemStack getItem(@Nonnull String id) {
        SlimefunItem item = SlimefunItem.getById(id);
        return item != null ? item.getItem() : null;
    }
}